import { DB } from '../store.js?v=canonical-20261006';
import { $, $$, esc, fmtEUR, fmtCcy, sum, uid, todayISO, num, toast } from '../util.js?v=canonical-20261006';
import { openAccForm } from '../forms.js?v=canonical-20261006';

export function renderCuentas(v, C) {
  v.innerHTML = `
    <div class="section-head"><h2>Cuentas</h2><button class="btn primary" id="newacc">+ Nueva cuenta</button></div>
    <div class="list">${DB.accounts.map(a => { const rows = C.rows.filter(r => r.accountId === a.id); const mv = sum(rows, r => r.mvEUR); const cash = C.cash[a.id] || {}; const cashEUR = (C.cashRaw && C.cashRaw[a.id] != null) ? C.cashRaw[a.id] : (C.cashEUR[a.id] || 0);
      return `<div class="card acc" data-acc="${a.id}"><div><div class="n">${esc(a.name)}</div><div class="d">${esc(a.broker || '')} · ${esc(a.country || '')}${a.multi_currency ? ' · multidivisa' : ''}${a.withholds_dest ? ' · retiene en destino' : ''} · ${rows.length} posiciones${a.notes ? ' · ' + esc(a.notes) : ''}</div></div>
        <div class="v"><div>${fmtEUR(mv, 0)} <span class="muted">posiciones</span></div><div class="${cashEUR < 0 ? 'neg' : ''}">${/sin caja/i.test(a.notes || '') ? `<span class="muted" title="Cuenta marcada «sin caja»: su efectivo no entra en el patrimonio ni en las rentabilidades">efectivo excluido (${fmtEUR(cashEUR, 0)} según operaciones)</span>` : fmtEUR(cashEUR, 0) + ' <span class="muted">efectivo</span>'}${cashEUR < -1 ? ' <span class="badge neg" title="Faltan ingresos por registrar: Filios no los guardaba. Este saldo no se resta del valor de la cartera.">faltan ingresos</span>' : ''}</div><div class="muted" style="font-size:.74rem">${Object.entries(cash).filter(([, x]) => Math.abs(x) > 0.005).map(([c, x]) => fmtCcy(x, c, 0)).join(' · ')}</div></div></div>`; }).join('') || '<div class="empty">Sin cuentas.</div>'}</div>
    <div class="card pad"><h3>Conciliar efectivo con el extracto</h3><div class="muted" style="font-size:.8rem">Indica el saldo real que muestra el bróker hoy. La diferencia se muestra para contrastarla con los movimientos originales. No se convierte automáticamente en un ingreso o retirada.</div><div class="form" style="margin-top:.5rem"><div class="field"><label>Cuenta</label><select id="rc-acc">${DB.accounts.filter(a => !/sin caja/i.test(a.notes || '')).map(a => `<option value="${a.id}">${esc(a.name)}</option>`).join('')}</select></div><div class="field"><label>Saldo real (€)</label><input type="number" step="any" id="rc-real" inputmode="decimal"></div><div class="field"><label>Fecha</label><input type="date" id="rc-date" value="${todayISO()}"></div><div class="field full"><label>Justificación</label><input type="text" id="rc-why" placeholder="Ingreso no registrado, intereses, comisión…"></div><div class="actions"><span class="muted" id="rc-diff" style="font-size:.8rem;margin-right:auto"></span><button class="btn primary" id="rc-save" disabled>Requiere conciliación documental</button></div></div></div>
    <div class="note warn">El efectivo sale de las operaciones. Filios agrupa en "Santander" las tres cuentas del banco (bróker, cartera gestionada y NEXTEP). Un saldo que no coincide requiere revisar omisiones, duplicados y movimientos originales. No se debe inventar una aportación para cuadrarlo. El motor conserva la diferencia calculada para revisión.</div>`;
  const rcDiff = () => { const a = $('#rc-acc').value; const calc = (C.cashRaw && C.cashRaw[a] != null) ? C.cashRaw[a] : (C.cashEUR[a] || 0); const real = num($('#rc-real').value); $('#rc-diff').textContent = $('#rc-real').value === '' ? `Calculado: ${fmtEUR(calc, 2)}` : `Calculado ${fmtEUR(calc, 2)} · real ${fmtEUR(real, 2)} · diferencia ${fmtEUR(real - calc, 2)}`; return { a, calc, real }; };
  $('#rc-acc').onchange = rcDiff; $('#rc-real').oninput = rcDiff; rcDiff();

  $('#newacc').onclick = () => openAccForm();
  $$('[data-acc]', v).forEach(el => el.onclick = () => openAccForm(DB.accounts.find(a => a.id === el.dataset.acc)));
}
